name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        echo $SHELL
        conda create -y -n pyspark_conda_env -c conda-forge pyarrow pandas conda-pack python==3.8.3
        source ~/.bashrc
        source activate
        conda deactivate
        conda activate pyspark_conda_env
        conda pack -f -o pyspark_conda_env.tar.gz
    - name: conda venv result
      uses: actions/upload-artifact@v4
      with:
        name: pyspark_conda_env.tar.gz
        path: pyspark_conda_env.tar.gz
